<?php

/*	Get eco-relevant book metadata from OAPEN.org.
	Uses oapen.json generated by convert.py (thanks, George!)
	that transforms the oapen.csv file that OAPEN makes
	available (thanks, OAPEN!).
	
	Amateur work done by an amateur
	Open licensed under MIT license
	david@weinberger.org
	Nov. 17, 2016
*/

$jsonfile = "oapen.json";

$jsonf = file_get_contents($jsonfile);
$json = json_decode($jsonf); 


// Add source metadata
$masterArray = array();
$masterArray["source"] = "OAPEN";
$masterArray["sourceUrl"] = "http://www.oapen.org";
$masterArray["dateUpdated"] = date("Y-m-d");
$books = array(); // array for sets of info about all the books


foreach($json as $book){

	if ($book->Language == "English"){
		// look for relevant books
		$keywords = $book->Keywords;
		$abstract = $book->Abstract;
		$title = $book->Title;
		$haystack = $keywords . $abstract;
	
		if (
			(stripos($haystack, "environment") > -1) ||
			(stripos($haystack, "ecolog") > -1) ||
			(stripos($haystack, "ecosystem") > -1) ||
			(stripos($haystack, "climate") > -1) ||
			(stripos($haystack, "conservation") > -1) ||
			(stripos($haystack, "desertification") > -1) ||
			(stripos($haystack, "sustainab") > -1) 
			)
			{
			// --- We have a relevant book
					// get item page and download page from OAPEN_URL
					//  which are concatenated, separated by |
					$concaturls = $book ->OAPEN_URL;
					$p = strpos($concaturls, "|");
					if ($p > -1){
						$itemPage = substr($concaturls, 0, $p - 1);
						$downloadPage = substr($concaturls, $p + 1);
					}
					else {
						$itemPage = "";
						$downloadPage = "";
					}
					// create array of tags
					$tagarray = explode("|",$keywords);
					// create array of authors
					$creators = explode("|",$book -> Creator);
			
					$bookarray	 = array (
							"title" => $book->Title,
							"language" => "ENGLISH",
							"abstract" => $book -> Abstract,
							"tags" => $tagarray,
							"creator" => $creators,
							"publisher" => $book -> Publisher,
							"place" => $book -> Place,
							"date" => $book -> Date,
							"extent" => array(array("unit" =>"pages", "quantity" => $book -> Pages)),
							"bic" => $book -> BIC_Classification,
							"keywords" => $book -> Keywords,
							"description" => $book -> Abstract,
							"seriesTitle" => $book -> SeriesTitle,
							"license" => $book -> Rights,
							"vendorItemPage" => $book -> Webshop,
							"seriesISSN" => $book -> SeriesISSN,
							"grant" => $book -> Grant,
							"GrantNumber" => $book -> GrantNumber,
							"id" => array( array( "source"=>"oapen_id", "id" => $book -> OAPEN_ID),
									array("source"=>"doi", "id" => $book -> DOI),
									array("source"=>"isbn", "id" => $book -> ISBN)
									),
							"itemPage" => $itemPage,
							"downloadPage" => $downloadPage
							);
				array_push($books, $bookarray);
				}

		}

	$masterArray["books"] = $books;
	
}


// ------ Save the file
$j = json_encode($masterArray);

$fname = "oaopenBooks.json";
 $fp = fopen($fname, 'w');
fwrite($fp,$j);
fclose($fp);

print "<p>File written: $fname";

return;



?>